include:
  - project: cloudnative/gitlab/gitlabci/terraform
    ref: v2.X
    file: .module.terraform.gitlab-ci.yml
  - project: cloudnative/gitlab/gitlabci/prometheus-testing-ci
    ref: v1.X
    file: .prometheus.gitlab-ci.yml

# Documentation: https://gitlab.k8s.cloud.statcan.ca/cloudnative/gitlab/gitlabci/terraform
# Support: https://gitlab.k8s.cloud.statcan.ca/cloudnative/gitlab/gitlabci/terraform#contribution-and-support
