apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: general-project-alerts
    role: general-project-alert-rules
    app: kube-prometheus-stack
    release: ${ helm_release }
  name: general-project-alerts
  namespace: ${ helm_namespace }
spec:
  groups:
  - name: containers.rules
    rules:
    - alert: ManyContainerRestarts
      expr: sum by(container, pod, namespace) (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 8h > 10)
      for: 2m
      labels:
        scope: project
        severity: major
      annotations:
        message: 'Container {{ $labels.namespace }}/{{ $labels.pod }}/{{ $labels.container }} restarted {{ $value }} times in the last 8 hours.'
    - alert: ContainerWaiting
      expr: sum by (container, pod, namespace, reason) (avg_over_time(kube_pod_container_status_waiting_reason{reason!="CrashLoopBackOff"}[15m:])) > 0.8
      for: 1h
      labels:
        scope: project
        severity: major
      annotations:
        message: 'Container {{ $labels.namespace }}/{{ $labels.pod }}/{{ $labels.container }} has been in {{ $labels.reason }} for over an hour.'
  - name: pods.rules
    rules:
    - alert: PodNotReady
      expr: sum by(namespace, pod) (max by(namespace, pod) (kube_pod_status_phase{job="kube-state-metrics",namespace=~".*",phase=~"Pending|Unknown"}) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"}))) > 0
      for: 15m
      labels:
        scope: project
        severity: major
      annotations:
        message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes.'
  - name: jobs.rules
    rules:
    - alert: CompletedJobsNotCleared
      expr: count by (namespace) (kube_job_status_completion_time < (time() - 86400)) > 20
      for: 15m
      labels:
        severity: major
        scope: project
      annotations:
        message: 'Namespace {{ $labels.namespace }} has {{ $value }} completed jobs older than 24h.'
    - alert: JobFailed
      expr: sum by(namespace, job_name) (kube_job_failed > 0)
      for: 15m
      labels:
        scope: project
        severity: major
      annotations:
        message: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete. Removing the failed job after investigation should clear this alert.'
    - alert: JobIncomplete
      expr: (sum by (namespace, job_name) (kube_job_spec_completions) unless sum by (namespace, job_name) (kube_job_complete == 1)) unless sum by (namespace, job_name) (kube_job_failed == 1)
      for: 12h
      labels:
        scope: project
        severity: major
      annotations:
        message: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than 12 hours to complete.'
